 
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author jordan
 */
public class Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LabelObservacao = new javax.swing.JLabel();
        LabelObservacao2 = new javax.swing.JLabel();
        LabelObservacao1 = new javax.swing.JLabel();
        LabelObservacao4 = new javax.swing.JLabel();
        JComboBoxServico2 = new javax.swing.JComboBox<>();
        TextFormatedData17 = new javax.swing.JFormattedTextField();
        TextFormatedData18 = new javax.swing.JFormattedTextField();
        TextFormatedData19 = new javax.swing.JFormattedTextField();
        TextFormatedData20 = new javax.swing.JFormattedTextField();
        LabelObservacao3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LabelId = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        TextFormatedData14 = new javax.swing.JFormattedTextField();
        LabelHora = new javax.swing.JLabel();
        LabelData2 = new javax.swing.JLabel();
        TextFormatedData2 = new javax.swing.JFormattedTextField();
        LabelData5 = new javax.swing.JLabel();
        LabelValor = new javax.swing.JLabel();
        LabelCliente1 = new javax.swing.JLabel();
        LabelData8 = new javax.swing.JLabel();
        LabelHora1 = new javax.swing.JLabel();
        TextFormatedData3 = new javax.swing.JFormattedTextField();
        TextFormatedData4 = new javax.swing.JFormattedTextField();
        TextFormatedData21 = new javax.swing.JFormattedTextField();
        TextFormatedData22 = new javax.swing.JFormattedTextField();
        LabelServico1 = new javax.swing.JLabel();
        JComboBoxServico1 = new javax.swing.JComboBox<>();
        TextFormatedData5 = new javax.swing.JFormattedTextField();
        TextFormatedData23 = new javax.swing.JFormattedTextField();
        LabelData6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ButtonAgendar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Funcionários");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        LabelObservacao.setBackground(new java.awt.Color(102, 255, 102));
        LabelObservacao.setForeground(new java.awt.Color(51, 51, 51));
        LabelObservacao.setText("Login");

        LabelObservacao2.setBackground(new java.awt.Color(102, 255, 102));
        LabelObservacao2.setForeground(new java.awt.Color(51, 51, 51));
        LabelObservacao2.setText("Confirmar Senha");

        LabelObservacao1.setBackground(new java.awt.Color(102, 255, 102));
        LabelObservacao1.setForeground(new java.awt.Color(51, 51, 51));
        LabelObservacao1.setText("Senha");

        LabelObservacao4.setBackground(new java.awt.Color(102, 255, 102));
        LabelObservacao4.setForeground(new java.awt.Color(51, 51, 51));
        LabelObservacao4.setText("Função");

        JComboBoxServico2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auxiliar de Dentista", "Clínico geral", "Gerente", "Protesista", "Recepcionista" }));
        JComboBoxServico2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboBoxServico2ItemStateChanged(evt);
            }
        });
        JComboBoxServico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxServico2ActionPerformed(evt);
            }
        });

        TextFormatedData17.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        TextFormatedData18.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        TextFormatedData19.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        TextFormatedData20.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        LabelObservacao3.setBackground(new java.awt.Color(102, 255, 102));
        LabelObservacao3.setForeground(new java.awt.Color(51, 51, 51));
        LabelObservacao3.setText("Salario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TextFormatedData20, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JComboBoxServico2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFormatedData19, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelObservacao1)
                            .addComponent(LabelObservacao3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelObservacao2)
                            .addComponent(TextFormatedData17, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelObservacao4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelObservacao)
                            .addComponent(TextFormatedData18, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(LabelObservacao)
                .addGap(18, 18, 18)
                .addComponent(TextFormatedData18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelObservacao2)
                    .addComponent(LabelObservacao1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFormatedData17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFormatedData19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelObservacao4)
                    .addComponent(LabelObservacao3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JComboBoxServico2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFormatedData20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 530, 390));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 255)));

        LabelId.setForeground(new java.awt.Color(51, 51, 51));
        LabelId.setText("Id");

        TextId.setEditable(false);
        TextId.setBackground(new java.awt.Color(204, 204, 204));
        TextId.setText("0");
        TextId.setToolTipText("");
        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });

        TextFormatedData14.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        LabelHora.setBackground(new java.awt.Color(51, 51, 51));
        LabelHora.setForeground(new java.awt.Color(51, 51, 51));
        LabelHora.setText("Endereço");

        LabelData2.setForeground(new java.awt.Color(51, 51, 51));
        LabelData2.setText("CPF");

        TextFormatedData2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TextFormatedData2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFormatedData2ActionPerformed(evt);
            }
        });

        LabelData5.setForeground(new java.awt.Color(51, 51, 51));
        LabelData5.setText("RG");

        LabelValor.setForeground(new java.awt.Color(51, 51, 51));
        LabelValor.setText("Telefone");

        LabelCliente1.setBackground(new java.awt.Color(51, 51, 51));
        LabelCliente1.setForeground(new java.awt.Color(51, 51, 51));
        LabelCliente1.setText("Nome");

        LabelData8.setForeground(new java.awt.Color(51, 51, 51));
        LabelData8.setText("Email");

        LabelHora1.setBackground(new java.awt.Color(51, 51, 51));
        LabelHora1.setForeground(new java.awt.Color(51, 51, 51));
        LabelHora1.setText("Nº");

        TextFormatedData3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TextFormatedData3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFormatedData3ActionPerformed(evt);
            }
        });

        TextFormatedData4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TextFormatedData4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFormatedData4ActionPerformed(evt);
            }
        });

        TextFormatedData21.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TextFormatedData21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFormatedData21ActionPerformed(evt);
            }
        });

        TextFormatedData22.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        LabelServico1.setForeground(new java.awt.Color(51, 51, 51));
        LabelServico1.setText("Sexo");

        JComboBoxServico1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        JComboBoxServico1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JComboBoxServico1ItemStateChanged(evt);
            }
        });
        JComboBoxServico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBoxServico1ActionPerformed(evt);
            }
        });

        TextFormatedData5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TextFormatedData5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFormatedData5ActionPerformed(evt);
            }
        });

        TextFormatedData23.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        LabelData6.setForeground(new java.awt.Color(51, 51, 51));
        LabelData6.setText("Data de Nascimento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(LabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(LabelCliente1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextFormatedData4, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFormatedData14, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(LabelHora)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelHora1)
                            .addComponent(TextFormatedData3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelData8)
                            .addComponent(TextFormatedData22, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LabelData2)
                                .addGap(165, 165, 165)
                                .addComponent(LabelData5)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JComboBoxServico1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelServico1))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(LabelValor)
                                        .addGap(58, 58, 58))
                                    .addComponent(TextFormatedData5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(LabelData6)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(TextFormatedData2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(TextFormatedData21, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFormatedData23, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelId)
                    .addComponent(LabelCliente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFormatedData4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelHora1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelHora))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFormatedData14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFormatedData3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelData8)
                            .addComponent(LabelServico1)
                            .addComponent(LabelValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JComboBoxServico1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFormatedData22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFormatedData5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LabelData2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelData5)
                            .addComponent(LabelData6))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFormatedData21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFormatedData2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextFormatedData23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 560, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 380, 10));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/daiii.png"))); // NOI18N
        jButton2.setText(" Fechar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, 160, 40));

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dados Acesso");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 530, 40));

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dados Pessoais");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 560, -1));

        ButtonAgendar1.setBackground(new java.awt.Color(102, 153, 255));
        ButtonAgendar1.setFont(new java.awt.Font("Cabin", 1, 18)); // NOI18N
        ButtonAgendar1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAgendar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/cadd.png"))); // NOI18N
        ButtonAgendar1.setText(" Cadastrar");
        ButtonAgendar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgendar1ActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAgendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JComboBoxServico2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboBoxServico2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxServico2ItemStateChanged

    private void JComboBoxServico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxServico2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxServico2ActionPerformed

    private void JComboBoxServico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBoxServico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBoxServico1ActionPerformed

    private void JComboBoxServico1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JComboBoxServico1ItemStateChanged
        // TODO add your handling code here:
        //this.Controller.atualizaValor();
    }//GEN-LAST:event_JComboBoxServico1ItemStateChanged

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    private void TextFormatedData2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFormatedData2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFormatedData2ActionPerformed

    private void TextFormatedData3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFormatedData3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFormatedData3ActionPerformed

    private void TextFormatedData4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFormatedData4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFormatedData4ActionPerformed

    private void TextFormatedData5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFormatedData5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFormatedData5ActionPerformed

    private void TextFormatedData21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFormatedData21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFormatedData21ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
             Object[] options = { "Sim", "Não", "Cancelar" }; 
        int i = JOptionPane.showOptionDialog(null, "Tem certeza que deseja fechar?", "Fechar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]); if (i == JOptionPane.YES_OPTION) { 
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ButtonAgendar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgendar1ActionPerformed
        // TODO add your handling code here:
        //this.Controller.agendar();
        Object[] options = { "Sim", "Não" };
        int i = JOptionPane.showOptionDialog(null, "Informe todos os campos para realizar a operação?", "OK", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]); if (i == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_ButtonAgendar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgendar1;
    private javax.swing.JComboBox<String> JComboBoxServico1;
    private javax.swing.JComboBox<String> JComboBoxServico2;
    private javax.swing.JLabel LabelCliente1;
    private javax.swing.JLabel LabelData2;
    private javax.swing.JLabel LabelData5;
    private javax.swing.JLabel LabelData6;
    private javax.swing.JLabel LabelData8;
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel LabelHora1;
    private javax.swing.JLabel LabelId;
    private javax.swing.JLabel LabelObservacao;
    private javax.swing.JLabel LabelObservacao1;
    private javax.swing.JLabel LabelObservacao2;
    private javax.swing.JLabel LabelObservacao3;
    private javax.swing.JLabel LabelObservacao4;
    private javax.swing.JLabel LabelServico1;
    private javax.swing.JLabel LabelValor;
    private javax.swing.JFormattedTextField TextFormatedData14;
    private javax.swing.JFormattedTextField TextFormatedData17;
    private javax.swing.JFormattedTextField TextFormatedData18;
    private javax.swing.JFormattedTextField TextFormatedData19;
    private javax.swing.JFormattedTextField TextFormatedData2;
    private javax.swing.JFormattedTextField TextFormatedData20;
    private javax.swing.JFormattedTextField TextFormatedData21;
    private javax.swing.JFormattedTextField TextFormatedData22;
    private javax.swing.JFormattedTextField TextFormatedData23;
    private javax.swing.JFormattedTextField TextFormatedData3;
    private javax.swing.JFormattedTextField TextFormatedData4;
    private javax.swing.JFormattedTextField TextFormatedData5;
    private javax.swing.JTextField TextId;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
