 
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author  jordan
 */
public class ListaFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public ListaFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAgendamentos = new javax.swing.JTable();
        LabelCliente = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        ButtonAgendar1 = new javax.swing.JButton();
        ButtonAgendar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Anna Dias", "Dentista", "4000,00", "05/12/1983", ""},
                {"2", "Camila Tavares", "Recepcionista", "1600,00", "29/11/2003", "Nenhuma"},
                {"3", "Juliana Souza", "Auxiliar Dentista", "2300,50", "23/10/1998", null},
                {"4", "Pedro Mattos", "Gerente", "8000,00", "19/10/1980", null},
                {"5", " Daniele Musta", "Auxiliar Dentista", "2300,50", "12/10/2005", null},
                {"6", "Fernando Paes", "Clinico Geral", "3800,00", "10/10/1986", null}
            },
            new String [] {
                "Id", "Nome", "Função", "Salario", "Data Nascimento", "Observação"
            }
        ));
        jScrollPane1.setViewportView(TableAgendamentos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 940, 320));

        LabelCliente.setBackground(new java.awt.Color(51, 51, 51));
        LabelCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelCliente.setForeground(new java.awt.Color(51, 51, 51));
        LabelCliente.setText("Lista de Funcionarios");
        jPanel1.add(LabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/daiii.png"))); // NOI18N
        jButton3.setText(" Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 130, 40));

        ButtonAgendar1.setBackground(new java.awt.Color(51, 153, 255));
        ButtonAgendar1.setFont(new java.awt.Font("Cabin", 1, 18)); // NOI18N
        ButtonAgendar1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAgendar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/cadd.png"))); // NOI18N
        ButtonAgendar1.setText(" Cadastrar");
        ButtonAgendar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgendar1ActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAgendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 160, 40));

        ButtonAgendar2.setBackground(new java.awt.Color(102, 255, 102));
        ButtonAgendar2.setFont(new java.awt.Font("Cabin", 1, 18)); // NOI18N
        ButtonAgendar2.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAgendar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/sevico-barnco.png"))); // NOI18N
        ButtonAgendar2.setText("  Alterar");
        ButtonAgendar2.setActionCommand(" Alterar");
        ButtonAgendar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgendar2ActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAgendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
             Object[] options = { "Sim", "Não", "Cancelar" }; 
        int i = JOptionPane.showOptionDialog(null, "Tem certeza que deseja fechar?", "Fechar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]); if (i == JOptionPane.YES_OPTION) { 
            this.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ButtonAgendar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgendar1ActionPerformed
        // TODO add your handling code here:
        //this.Controller.agendar();
    }//GEN-LAST:event_ButtonAgendar1ActionPerformed

    private void ButtonAgendar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgendar2ActionPerformed
        // TODO add your handling code here:
        //this.Controller.agendar();
        Object[] options = { "Sim", "Não"};
        int i = JOptionPane.showOptionDialog(null, "Deseja realizar uma alteração no funcionario", "Sim", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]); if (i == JOptionPane.YES_OPTION) {
            this.dispose();
        }

    }//GEN-LAST:event_ButtonAgendar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgendar1;
    private javax.swing.JButton ButtonAgendar2;
    private javax.swing.JLabel LabelCliente;
    private javax.swing.JTable TableAgendamentos;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
